### ISSUE TITLE
Description file: LICENSE-files

### ISSUE THREAD

**Issue by jasdumas** [r-devel/cran-cookbook#29]
All licenses must be FOSS (there is a list here: https://svn.r-project.org/R/trunk/share/licenses/license.db)!
Most licenses don’t need an additional file as these are part of R. If one is added anyways, we will reject. 
Same goes for MIT-License files with wrongly specified copyright holders. Surprisingly often, package authors write “[packagename] authors” (which is fine) but still list an old/outdated packagename.

**Comment by jasdumas** [comment]
_I converted this project ticket to an issue to ask some clarifying questions_

@Baltmann01 Is this a new rejection rule? 

I'm looking at my own [DESCRIPTION file](https://github.com/jasdumas/shinyLP/blob/master/DESCRIPTION#L16) for `shinyLP` that was updated/accepted to CRAN 9 months ago and I have a reference to a [LICENSE file](https://github.com/jasdumas/shinyLP/blob/master/LICENSE):

```
License: MIT + file LICENSE

```

Would this way of writing it currently get rejected?

**Comment by llrs** [comment]
What you have is a template for the relevant aspects of the MIT license (author and date). 
It would be rejected if you had a [full MIT license](https://choosealicense.com/licenses/mit/) copied and submitted. CRAN maintainers do not want to add 25k MIT license files duplicated. 
The rule is relatively old, but recently it has been enforced via checks that packages comply with [CRAN templates](https://cran.r-project.org/web/licenses/).

**Comment by Baltmann01** [comment]
Yeah, exactly. We on CRAN don't want several copies of the same LICENSE files if the file is already part of R. The MIT License needs however an additional file which specifies the Author and Year. So no worries, MIT + file LICENSE is exactly what you need. 
If you check out this webpage: https://svn.r-project.org/R/trunk/share/licenses/license.db you can see for the MIT license it says:
"Note: this is a template, needs + file LICENSE"

**Comment by llrs** [comment]
~~I'm surprised this license.db is in R source code and not somewhat accessible from R side.~~
If it helps to document this (I just learned about `RShowDoc()`), the list can be consulted via:

```r
path_licenses <- RShowDoc("license.db")
licenses_doc <- as.data.frame(read.dcf(path_licenses))
```
