### ISSUE TITLE
Description file: Description Length

### ISSUE THREAD

**Issue by jasdumas** [r-devel/cran-cookbook#39]
The description in the DESCRIPTION file should be a short paragraph on what the package is all about (preferably including further references). Sometimes I see descriptions which are only a short sentence or the title of the package repeated. We would like description texts to be CRAN package equivalents to cover texts of books or abstracts of papers.

**Comment by Baltmann01** [comment]
There is no automatic NOTE produced as it is difficult to automatically set some form of threshold. Amount of words/sentences does not really make sense there and some packages do  not need a very long description (e.g.: API wrappers and such). 

I guess we can add a section about the description in the general section and include this issue there.

**Comment by jasdumas** [comment]
Thanks for your input...I'll think a bit more about this too and find an appropriate section to move this to.
