### ISSUE TITLE
Text boxes with CRAN templates

### ISSUE THREAD

**Issue by Baltmann01** [r-devel/cran-cookbook#44]
In our last Sync meeting we talked ybout adding the template we use on CRAN to each recipe. I now created a test version of that for the tempdir() issue, where I simplified a standard callout-note and made it collapsible. 

Should we stick with this design or create our own callout box for this?

**Comment by jasdumas** [comment]
It would also be great to write an overview of these callout notes for the **[CRAN Review Communication](https://contributor.r-project.org/cran-cookbook/code_issues.html#details-9)** in the preface or general section

**Comment by jasdumas** [comment]
#66 related

**Comment by Baltmann01** [comment]
As #66 is published, I will close this issue. Small note: @jasdumas, maybe we should add in the (future) contributor guidelines that recipes ideally have the error, note or CRAN communication as callout box?
