### ISSUE TITLE
Authorship of third-party code

### ISSUE THREAD

**Issue by aitap** [r-devel/cran-cookbook#45]
Every now and then, there is a need to directly include third-party code in an R package without a way to link to an external build of it as recommended by the policy. Here's a recent example: [R-package-devel thread](https://stat.ethz.ch/pipermail/r-package-devel/2024q3/010965.html), eventual [CRAN package](https://cran.r-project.org/package=speakeasyR) with lots of `cph, ctb` co-authors. After a recent [change in `?person`](https://github.com/r-devel/r-svn/commit/4219aef12fc16017f72bc71f38d9c2942fe3a7fc), all the "natural person" co-authors are automatically considered `cph`. Do I understand it correctly that the correct way to include third-party code now is as follows?

1. [Try to find a way not to](https://stat.ethz.ch/pipermail/r-package-devel/2024q3/010969.html)
2. Locate all co-authors and copyright holders, possibly reading the version control history if the project doesn't provide an official list of authors
3. Mark "natural person" co-authors as `ctb`, organisations as `cph, ctb`
4. For multiple `cph` co-authors, specify the ownership details in the `comment` argument

**Comment by llrs** [comment]
I think this should be first addressed at r-package-devel as it affects also packages on Bioconductor. Note that there was also some change on how `comment` is used (not sure what was the intention but saw some commits about it).

**Comment by aitap** [comment]
My apologies, I had assumed that the presence of a CRAN team member offered a more direct way of clarifying rules. Let's hope that after an R-package-devel discussion we'll be able to make it into a pull request.

**Comment by llrs** [comment]
There is nothing to apology, I might be wrong. The [CRAN team](https://cran.r-project.org/CRAN_team.htm) is divided in groups, and I don't think the CRAN QA group is checking this repository. I think they are more likely to see this on the mailing list.

**Comment by jasdumas** [comment]
Hi @aitap, Thanks for your question. I'm going to be writing up a somewhat relevant recipe issue: [Description file: Using Authors@R](https://github.com/orgs/r-devel/projects/3?pane=issue&itemId=66852185) soon and I'll take some time to think about how this question can be answered and included as a callout note at least for reference.

**Comment by aitap** [comment]
Thank you! I see [the policy for organisations is being updated as well](https://github.com/r-devel/r-dev-web/commit/a8dd70789d8e5fb53b6aec72fe242d4c33e970aa).

**Comment by Baltmann01** [comment]
Small comment from my side as CRAN newbie submission team member:
Your list looks like a great summary.  I can only tell you what I look for in packages with third-party code.
And packages following your list would probably pass my review (at least regarding this issue).
