### ISSUE TITLE
Add CRAN survey results to wiki

### ISSUE THREAD

**Issue by jasdumas** [r-devel/cran-cookbook#47]
[Wiki](https://github.com/r-devel/cran-cookbook/wiki)

**Comment by jasdumas** [comment]
https://github.com/orgs/r-devel/projects/3/views/1?pane=issue&itemId=79917854

**Comment by llrs** [comment]
Many thanks for sharing the results of the survey.
Can we share this broadly? (Emailing lists, slack, mastodon...) or would you prefer to share this yourself? 

I think there were some quantitative questions, the number of packages developed or something similar. Will this be shared? Or I am misremembering this

Is there an estimation to when will you contact people?
