### ISSUE TITLE
Schedule the next team meeting

### ISSUE THREAD

**Issue by jasdumas** [r-devel/cran-cookbook#48]
Potentially the 3rd week of October?

**Comment by hturner** [comment]
That week is generally free for me, though Friday is tentative. There will be an R Contribution Working Group meeting at 6:30pm UTC on Tuesday 15 October, so please avoid being too close to that.

**Comment by nzgwynn** [comment]
At this point, my schedule is open all mornings that week.

**Comment by bettinagruen** [comment]
Next week the following would work for me (in CEST):

Monday afternoon
Tuesday after 3pm
Friday afternoon
